CREATE TABLE SENSOR_INFO (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	LOG_TIME TIMESTAMP,
	TEMPERATURE REAL,
	HUMIDITY REAL,
	LIGHT REAL,
	SOUND REAL,
	PROXIMITY REAL,
	THRESHOLD INTEGER);

ALTER TABLE SENSOR_INFO ADD PRIMARY KEY (ID);
